apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmsa-webhook.fullname" . }}
  labels:
    {{- include "llmsa-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
  selector:
    {{- include "llmsa-webhook.selectorLabels" . | nindent 4 }}
