apiVersion: v1
kind: Service
metadata:
  name: llmsa-webhook
  namespace: llmsa-system
  labels:
    app: llmsa-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: llmsa-webhook
